# Travis CI build file for CircuitBreaker.
# CircuitBreaker runs on OS X and Linux (Ubuntu).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
      sudo: required
      env: SWIFT_SNAPSHOT=2.2
    - os: osx
      osx_image: xcode8
      sudo: required
      env: SWIFT_SNAPSHOT=3.0
    - os: osx
      osx_image: xcode8.1
      sudo: required
      env: SWIFT_SNAPSHOT=3.0
    - os: osx
      osx_image: xcode8.2
      sudo: required
      env: SWIFT_SNAPSHOT=3.0.2
    - os: osx
      osx_image: xcode8.3
      sudo: required
      env: SWIFT_SNAPSHOT=3.1.1
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0

before_install:
  - git clone https://github.com/sandmman/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
